spring:
 security:
  oauth2:
    client:
      registration:
        #          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
        #            client-id: 머시기
        #            client-secret: 머시기
        #            scope:
        #              - email
        #              - profile

        facebook: # raidho test version
          client-id: 7952472958159822
          client-secret: 539c322cc08790eda00edab9cf3a4653
          scope:
            - email
            - public_profile

        # 네이버는 OAuth2.0 공식 지원대상이 아니라서 provider 설정이 필요하다.
        # 요청주소도 다르고, 응답 데이터도 다르기 때문이다.

        naver:
          client-id: Hckxb_WJxDGBqLIrztVk
          client-secret: NaftaemDLI
          scope:
            - name
            - email
          client-name: Naver
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/naver

        kakao:
          client-id: d1cc1bbcdc76ccb1f758840003c013ee
          client-secret: FFemeCXNfqXhyrPoZfqB7vY57bjFM12n
          scope:
            - profile_nickname
            - account_email
          client-name: Kakao
          authorization-grant-type: authorization_code
          redirect-uri: http://localhost:8080/login/oauth2/code/kakao


      provider:
        naver:
          authorization-uri: https://nid.naver.com/oauth2.0/authorize
          token-uri: https://nid.naver.com/oauth2.0/token
          user-info-uri: https://openapi.naver.com/v1/nid/me
          user-name-attribute: response

        kakao:
          authorization_uri: https://kauth.kakao.com/oauth/authorize
          token_uri: https://kauth.kakao.com/oauth/token
          user-info-uri: https://kapi.kakao.com/v2/user/me
          user_name_attribute: id